import NavBar from "@/components/navBar";
import "./globals.css";

export const metadata = {
  title: "New Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        <main className='container mx-auto h-[calc(100vh-4rem)] flex justify-center items-center'>
          {children}
        </main>
      </body>
    </html>
  );
}

export default RootLayout;